services:
  - name: soap-service
    type: web
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python soap_service.py"
    runtime: python-3.11.9
